# Generated by Django 5.1 on 2024-08-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_document_assigned_to_document_from_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="owner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
