# Generated by Django 5.1 on 2024-08-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_document_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="owner",
        ),
    ]
