# Generated by Django 4.0.8 on 2024-08-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_remove_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('AIP', 'AIP'), ('Advisory', 'Advisory'), ('Application Letter', 'Application Letter'), ('Authority to Travel', 'Authority to Travel'), ('COC-DPWH', 'COC-DPWH'), ('Certificate of No Pending Case', 'Certificate of No Pending Case'), ('Class Observation Plan', 'Class Observation Plan'), ('Communications', 'Communications'), ('Conduct Research', 'Conduct Research'), ('Daily Time Record (DTR)', 'Daily Time Record (DTR)'), ('Designation Letter', 'Designation Letter'), ('Disbursement Voucher', 'Disbursement Voucher'), ('Division Clearance', 'Division Clearance'), ('ERF', 'ERF'), ('Endorsement of Transfer to other Division', 'Endorsement of Transfer to other Division'), ('Fidelity Bond', 'Fidelity Bond'), ('GSIS Maturity & Retirement Form', 'GSIS Maturity & Retirement Form'), ('Instructional Supervisory Plan', 'Instructional Supervisory Plan'), ('Itinerary of Travel', 'Itinerary of Travel'), ('Job Order', 'Job Order'), ('Leave Application', 'Leave Application'), ('Legal Documents', 'Legal Documents')], default='Communications', max_length=50),
        ),
    ]
