# Generated by Django 4.0.8 on 2024-08-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_document_other_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived'), ('disable', 'Disable')], default='in_progress', max_length=20),
        ),
    ]
